name: Build Android APK (Offline App)
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Create Android platform folders
        run: flutter create . --platforms=android
      - run: flutter pub get
      - name: Build release APK
        run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: alkady-prioritizer-apk
          path: build/app/outputs/flutter-apk/app-release.apk
